services:
  music-sub:
    image: music-sub:0.6.23
    build: .
    container_name: music-sub
    ports:
      - "8400:8400"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./data/downloads:/downloads/music
      - ./data/library:/music
    environment:
      - MUSIC_SUB_CONFIG=/app/config/config.yaml
      - MUSIC_SUB_DB=/app/data/music_sub.db
      - no_proxy=*
      - NO_PROXY=*
    dns:
      - 223.5.5.5
      - 119.29.29.29
      - 8.8.8.8
    depends_on:
      - qbittorrent
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: music-sub-qb
    ports:
      - "8401:8080"
      - "57881:57881"
      - "57881:57881/udp"
    volumes:
      - ./data/qb-config:/config
      - ./data/downloads:/downloads/music
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=57881
    restart: unless-stopped
